# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('light_jets', '0002_auto_20190320_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='light_jets.Product'),
        ),
    ]
