# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light_jets', '0003_auto_20190320_0410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tracking',
            unique_together=set([('product', 'track_datetime', 'latitude', 'longitude')]),
        ),
    ]
