# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('light_jets', '0004_auto_20190320_0523'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('product_id', 'description')]),
        ),
    ]
